// Generated by CoffeeScript 1.10.0
(function() {
  var WebSocketClientConnection, ws;

  WebSocketClientConnection = require('../src/ws').WebSocketClientConnection;

  ws = new WebSocketClientConnection('ws://echo.websocket.org');

  ws.readyState;

  ws.on('close', function(code) {
    return console.log("Socket closed", code);
  });

  ws.on('data', function(opcode, data) {
    return console.log("OPCODE:", opcode, "DATA:", data);
  });

}).call(this);
