// Generated by CoffeeScript 1.10.0
(function() {
  var randomNum;

  randomNum = function(len) {
    var n;
    return parseInt(((function() {
      var i, ref, results;
      results = [];
      for (n = i = 1, ref = len; 1 <= ref ? i <= ref : i >= ref; n = 1 <= ref ? ++i : --i) {
        results.push((Math.floor(Math.random() * 10)).toString());
      }
      return results;
    })()).join(''));
  };

}).call(this);
