// Generated by CoffeeScript 1.6.3
(function() {
  var Router, context, ct, tpl1, tpl2;

  Router = require('../src/router');

  ct = new Router().compile_template;

  context = {
    name: 'Sandy',
    age: 59,
    children: [
      {
        name: 'Jorge',
        age: 32
      }, {
        name: 'Sol',
        age: 29
      }, {
        name: 'Celeste',
        age: 26
      }
    ]
  };

  tpl1 = "<h1>Hi, this is {{name}} page!</h1>\n<p>And these are my children</p>\n<ul>\n{{#children}}\n  <li>{{name}} - {{age}}</li>\n{{/children}}\n</ul>\n<h3>Hobbies</h3>\n{{#hobbies}} <p> I like {{ hobbies }} </p> {{/hobbies}}\n{{^hobbies}} Regretably no hobbies so far... ;-( {{/hobbies}}\n<hr/>";

  tpl2 = "<p>Hi, I am {{name}}</p>";

  module.exports = {
    ct: ct,
    context: context,
    tpl1: tpl1,
    tpl2: tpl2
  };

  console.log(ct(tpl1, context));

  console.log("\n----------------------------------------\n");

  context.hobbies = "Chess";

  console.log(ct(tpl1, context));

}).call(this);
