// Generated by CoffeeScript 1.10.0
(function() {
  var uuid;

  uuid = function() {
    var d, guid;
    d = new Date().getTime();
    guid = "xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g, function(c) {
      var r;
      r = (d + Math.random() * 16) % 16 | 0;
      d = Math.floor(d / 16);
      return (c === "x" ? r : r & 0x7 | 0x8).toString(16);
    });
    return guid;
  };

  if (typeof module !== "undefined" && module !== null) {
    module.exports = uuid;
  }

}).call(this);
