// Generated by CoffeeScript 1.6.3
(function() {
  var Router, argv, http, router, server;

  Router = require('../src/router');

  http = require('http');

  router = Router({
    list_dir: true
  });

  router.get("/hello", function(req, res) {
    return res.end('Hello, World!, Hola, Mundo!');
  });

  router.get("/users", function(req, res) {
    res.writeHead(200, {
      'Content-type': 'text/html'
    });
    return res.end('<h1 style="color: navy; text-align: center;">Active members registry</h1>');
  });

  router.get("/users/:id", function(req, res) {
    res.writeHead(200, {
      'Content-type': 'text/html'
    });
    return res.end("<h1>User No: <span style='color: red;'>" + req.params.id + "</span></h1>");
  });

  argv = process.argv.slice(2);

  server = http.createServer(router);

  server.on('listening', function() {
    var addr;
    addr = server.address() || {
      address: '0.0.0.0',
      port: argv[0] || 8000
    };
    return router.log("Serving web content at " + addr.address + ":" + addr.port);
  });

  process.on("SIGINT", function() {
    server.close();
    router.log(' ');
    router.log("Server shutting up...");
    router.log(' ');
    return process.exit(0);
  });

  server.listen((argv[0] != null) && !isNaN(parseInt(argv[0])) ? parseInt(argv[0]) : 8000);

}).call(this);
